package es.art83.ticTacToe.models.entities;

import java.util.ArrayList;
import java.util.List;

import es.art83.ticTacToe.models.utils.ColorModel;

public class TestBoardEntityListOfPieceEntityData {

    private List<List<PieceEntity>> piecesBoardSet = new ArrayList<List<PieceEntity>>();

    public TestBoardEntityListOfPieceEntityData() {

        final ColorModel[][] PUT_COLORS_BOARD_SET = { {}, {ColorModel.X},
                {ColorModel.X, ColorModel.O}, {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}, {},
                {ColorModel.X}, {ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O},
                {ColorModel.X, ColorModel.X, ColorModel.X, ColorModel.O, ColorModel.O}};

        final int[][][] PUT_INT_INTS_BOARD_SET = { {}, {{0, 0}}, { {0, 0}, {1, 0}},
                { {0, 0}, {0, 1}, {1, 0}}, { {0, 0}, {0, 1}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}},
                { {0, 0}, {0, 1}, {0, 2}, {1, 0}, {1, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}, {}, {{1, 0}}, { {1, 0}, {2, 0}},
                { {1, 0}, {1, 1}, {2, 0}}, { {1, 0}, {1, 1}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}},
                { {1, 0}, {1, 1}, {1, 2}, {2, 0}, {2, 1}}};
        assert (PUT_COLORS_BOARD_SET.length == PUT_INT_INTS_BOARD_SET.length);

        for (int i = 0; i < PUT_COLORS_BOARD_SET.length; i++) {
            List<PieceEntity> piecesBoard = new ArrayList<PieceEntity>();
            for (int j = 0; j < PUT_COLORS_BOARD_SET[i].length; j++) {
                piecesBoard.add(new PieceEntity(PUT_COLORS_BOARD_SET[i][j], new CoordinateEntity(
                        PUT_INT_INTS_BOARD_SET[i][j][0], PUT_INT_INTS_BOARD_SET[i][j][1])));
            }
            piecesBoardSet.add(piecesBoard);
        }
    }

    public List<List<PieceEntity>> getPiecesBoardSet() {
        return piecesBoardSet;
    }
}
